# Centralized pipeline definitions
include:
  - project: games/ci/gaas-pipeline-templates
    ref: master
    file: basic_game.yml

# Required variables on a per-game basis.
variables:
  WEB_NAME: pickngopokerdeuceswild
  BACKEND_ID: villitkakkoset
  BACKEND_VERSION: 1.0.0-1738660011-SNAPSHOT

