# Centralized pipeline definitions
include:
  - project: games/ci/gaas-pipeline-templates
    ref: master
    file: basic_game.yml

# Required variables on a per-game basis.
variables:
  BACKEND_ID: dragonsolitaire
  # A valid WEB_NAME must:
  # - Consist of only characters [0-9a-z-].
  # - Start with a letter.
  # - End with either a letter or digit.
  # - Be at most 32 characters long.
  WEB_NAME: dragonsolitaire
  BACKEND_VERSION: 1.0.0-1775652608-SNAPSHOT
