import {fx} from '@apila/game-libraries';

export const FX_DEFS: fx.FxJsonFile = {
  handlers: {
    sound: {
      type: 'SoundHandler',
      assets: {
        bet: [
          'button_bet_1',
          'button_bet_2',
          'button_bet_3',
          'button_bet_4',
          'button_bet_5',
          'button_bet_6',
          'button_bet_7',
          'button_bet_8',
          'button_bet_9',
          'button_bet_10',
          'button_bet_11',
          'button_bet_12',
          'button_bet_13',
          'button_bet_14',
          'button_bet_15',
        ],
        button_press: 'button_press',
        button_release: 'button_release',

        collect_cards: 'collect_cards',
        deal_cards: 'deal_cards',
        reveal_cards: 'reveal_cards',
        select_cards: 'select_cards',
        set_volume: 'set_volume',
        sort_swap: 'sort_swap',
        super_music: 'super_music',
        super_round: 'super_round',
        win_sound: 'win_sound',

        basic_win_scrolling_loop: 'win_scroll_loop',
        win_scrolling_stop: 'win_scrolling_stop',
        end_win_scrolling: 'win_big_rising',
        end_win_text_appears_1: 'big_win_text_appear_1',
        end_win_text_appears_2: 'big_win_text_appear_2',
        end_win_text_appears_3: 'big_win_text_appear_3',
        win_scroll_end_small: 'win_scroll_end_small',
        win_scroll_end_big: 'win_scroll_end_big',
        win_small: 'win_small',
        win_big: 'win_big',
        win_highlight: 'win_highlight',

        dbl_win: 'dbl_win',
        dbl_lose: 'dbl_lose',
        dbl_guess: [
          'dbl_guess_0',
          'dbl_guess_1',
          'dbl_guess_2',
          'dbl_guess_3',
          'dbl_guess_4',
        ],
        dbl_query: [
          'dbl_query_0',
          'dbl_query_1',
          'dbl_query_2',
          'dbl_query_3',
          'dbl_query_4',
        ],
      },
    },
  },

  events: {
    fx_bet_0: {target: 'sound', action: 'play', asset: 'bet', index: 0},
    fx_bet_1: {target: 'sound', action: 'play', asset: 'bet', index: 1},
    fx_bet_2: {target: 'sound', action: 'play', asset: 'bet', index: 2},
    fx_bet_3: {target: 'sound', action: 'play', asset: 'bet', index: 3},
    fx_bet_4: {target: 'sound', action: 'play', asset: 'bet', index: 4},
    fx_bet_5: {target: 'sound', action: 'play', asset: 'bet', index: 5},
    fx_bet_6: {target: 'sound', action: 'play', asset: 'bet', index: 6},
    fx_bet_7: {target: 'sound', action: 'play', asset: 'bet', index: 7},
    fx_bet_8: {target: 'sound', action: 'play', asset: 'bet', index: 8},
    fx_bet_9: {target: 'sound', action: 'play', asset: 'bet', index: 9},
    fx_bet_10: {target: 'sound', action: 'play', asset: 'bet', index: 10},
    fx_bet_11: {target: 'sound', action: 'play', asset: 'bet', index: 11},
    fx_bet_12: {target: 'sound', action: 'play', asset: 'bet', index: 12},
    fx_bet_13: {target: 'sound', action: 'play', asset: 'bet', index: 13},
    fx_bet_14: {target: 'sound', action: 'play', asset: 'bet', index: 14},
    fx_button_press: {target: 'sound', action: 'play', asset: 'button_press'},
    fx_button_release: {
      target: 'sound',
      action: 'play',
      asset: 'button_release',
    },

    fx_collect_cards: {
      target: 'sound',
      action: 'play',
      asset: 'collect_cards',
    },
    fx_deal_cards: {target: 'sound', action: 'play', asset: 'deal_cards'},
    fx_reveal_cards: {target: 'sound', action: 'play', asset: 'reveal_cards'},
    fx_select_cards: {target: 'sound', action: 'play', asset: 'select_cards'},
    fx_set_volume: {target: 'sound', action: 'play', asset: 'set_volume'},
    fx_sort_swap: {target: 'sound', action: 'play', asset: 'sort_swap'},
    fx_super_start: [
      {
        target: 'sound',
        action: 'play',
        asset: 'super_music',
        loop: true,
        fade: 1.5,
      },

      {target: 'sound', action: 'play', asset: 'super_round'},
    ],
    fx_super_end: {
      target: 'sound',
      action: 'stop',
      asset: 'super_music',
      fade: 1.0,
    },
    fx_win_sound: {target: 'sound', action: 'play', asset: 'win_sound'},

    // win scroller
    fx_winsum_scrolling_start: [
      {
        target: 'sound',
        action: 'play',
        loop: true,
        asset: 'basic_win_scrolling_loop',
      },
    ],
    fx_winsum_noscroll: {target: 'sound', action: 'play', asset: 'win_small'},
    fx_winsum_small: {target: 'sound', action: 'play', asset: 'win_small'},
    fx_winsum_big: {target: 'sound', action: 'play', asset: 'win_big'},
    fx_winsum_scrolling_stop_small: [
      {target: 'sound', action: 'play', asset: 'win_scroll_end_small'},
      {
        target: 'sound',
        action: 'stop',
        fade: 0.05,
        asset: 'basic_win_scrolling_loop',
      },
    ],
    fx_winsum_scrolling_stop_big: [
      {
        target: 'sound',
        action: 'stop',
        fade: 0.2,
        asset: 'end_win_scrolling',
      },
      {target: 'sound', action: 'play', asset: 'win_scroll_end_big'},
      {
        target: 'sound',
        action: 'stop',
        fade: 0.05,
        asset: 'basic_win_scrolling_loop',
      },
    ],

    fx_winsum_scrolling_bg_start: [
      {target: 'sound', action: 'play', asset: 'end_win_scrolling'},
    ],

    fx_end_win_text_appears_0: [
      {target: 'sound', action: 'play', asset: 'end_win_text_appears_1'},
    ],
    fx_end_win_text_appears_1: [
      {target: 'sound', action: 'play', asset: 'end_win_text_appears_1'},
    ],
    fx_end_win_text_appears_2: [
      {target: 'sound', action: 'play', asset: 'end_win_text_appears_2'},
    ],
    fx_end_win_text_appears_3: [
      {target: 'sound', action: 'play', asset: 'end_win_text_appears_3'},
    ],

    // Gamble
    fx_dbl_win: {target: 'sound', action: 'play', asset: 'dbl_win'},
    fx_dbl_lose: {target: 'sound', action: 'play', asset: 'dbl_lose'},
    fx_dbl_guess_0: {
      target: 'sound',
      handle: 'dbl_guess',
      action: 'play',
      asset: 'dbl_guess',
      loop: true,
      index: 0,
    },
    fx_dbl_guess_1: {
      target: 'sound',
      handle: 'dbl_guess',
      action: 'play',
      asset: 'dbl_guess',
      loop: true,
      index: 1,
    },
    fx_dbl_guess_2: {
      target: 'sound',
      handle: 'dbl_guess',
      action: 'play',
      asset: 'dbl_guess',
      loop: true,
      index: 2,
    },
    fx_dbl_guess_3: {
      target: 'sound',
      handle: 'dbl_guess',
      action: 'play',
      asset: 'dbl_guess',
      loop: true,
      index: 3,
    },
    fx_dbl_guess_4: {
      target: 'sound',
      handle: 'dbl_guess',
      action: 'play',
      asset: 'dbl_guess',
      loop: true,
      index: 4,
    },
    fx_dbl_query_0: {
      target: 'sound',
      action: 'play',
      handle: 'dbl_query',
      asset: 'dbl_query',
      loop: true,
      index: 0,
    },
    fx_dbl_query_1: {
      target: 'sound',
      action: 'play',
      handle: 'dbl_query',
      asset: 'dbl_query',
      loop: true,
      index: 1,
    },
    fx_dbl_query_2: {
      target: 'sound',
      action: 'play',
      handle: 'dbl_query',
      asset: 'dbl_query',
      loop: true,
      index: 2,
    },
    fx_dbl_query_3: {
      target: 'sound',
      action: 'play',
      handle: 'dbl_query',
      asset: 'dbl_query',
      loop: true,
      index: 3,
    },
    fx_dbl_query_4: {
      target: 'sound',
      action: 'play',
      handle: 'dbl_query',
      asset: 'dbl_query',
      loop: true,
      index: 4,
    },
    fx_dbl_guess_stop: {
      target: 'sound',
      action: 'stop',
      handle: 'dbl_guess',
      fade: 0.5,
    },
    fx_dbl_query_stop: {
      target: 'sound',
      action: 'stop',
      handle: 'dbl_query',
      fade: 1,
    },

    fx_empty: [],
  },
};
